### ISSUE TITLE
Plagiarism

### ISSUE THREAD

**Issue by SatoX69** [jarif098/SYNTAX-BOT#1]
Stop plagiarizing, 97% of this entire code is by [NTKhang](https://github.com/ntkhang03/)

**Comment by jarif098** [comment]
do you have any problem?

**Comment by jarif098** [comment]
> Stop plagiarizing, 97% of this entire code is by [NTKhang](https://github.com/ntkhang03/)

do you have any problem?

**Comment by SatoX69** [comment]
> > Stop plagiarizing, 97% of this entire code is by [NTKhang](https://github.com/ntkhang03/)
> 
> do you have any problem?

Ye, I do retard
